#ifndef ERROR_REPLIES_H
#define ERROR_REPLIES_H

/******************************************************************************
* error messages
******************************************************************************/
#define ERR_NOSUCHNICK 			401
#define ERR_NOSUCHSERVER 		402
#define ERR_NOSUCHCHANNEL		403
#define ERR_CANNOTSENDTOCHAN	404
#define ERR_TOOMANYCHANNELS		405
#define ERR_TOOMANYTARGETS 		407
#define ERR_NORECIPIENT			411
#define ERR_NOTEXTTOSEND 		412
#define ERR_UNKNOWNCOMMAND 		421
#define ERR_NOMOTD				422
#define ERR_NONICKNAMEGIVEN		431
#define ERR_ERRONEUSNICKNAME	432
#define ERR_NICKNAMEINUSE		433
#define ERR_NICKCOLLISION		436
#define ERR_UNAVAILRESOURCE		437
#define ERR_USERNOTINCHANNEL	441
#define ERR_NOTONCHANNEL		442
#define ERR_USERONCHANNEL 		443
#define ERR_NOLOGIN				444
#define ERR_USERSDISABLED		446
#define ERR_NOTREGISTERED		451
#define ERR_NEEDMOREPARAMS		461
#define ERR_ALREADYREGISTRED	462
#define ERR_NOPERMFORHOST		463
#define ERR_PASSWDMISMATCH		464
#define ERR_KEYSET				467
#define ERR_CHANNELISFULL 		471
#define ERR_UNKNOWNMODE			472
#define ERR_INVITEONLYCHAN		473
#define ERR_BANNEDFROMCHAN 		474
#define ERR_BADCHANNELKEY		475
#define ERR_NOCHANMODES			477
#define ERR_BANLISTFULL 		478
#define ERR_NOPRIVILEGES 		481
#define ERR_CHANOPRIVSNEEDED 	482
#define ERR_RESTRICTED 			484

#endif